{
  "services": [
    {
      "type": "web",
      "name": "kenzup-backend",
      "env": "node",
      "rootDir": "backend",
      "buildCommand": "npm install",
      "startCommand": "npm start",
      "envVars": [
        {
          "key": "MONGODB_URI",
          "value": "mongodb+srv://simoaglaou0_db_user:BURbRKph5NppIsKM@cluster0.zixukd6.mongodb.net/kenzup"
        },
        {
          "key": "JWT_SECRET",
          "value": "your-super-secret-jwt-key-12345"
        },
        {
          "key": "JWT_EXPIRE",
          "value": "7d"
        },
        {
          "key": "NODE_ENV",
          "value": "production"
        }
      ]
    }
  ]
}
